version: '3'

services:
  selenium-app:
    container_name: selenium-app
    build: 
      context: .
      dockerfile: dockerfile
    depends_on:
      - selenium-hub  # Dependência para o serviço do hub Selenium
    environment:
      - HUB_HOST=selenium-hub  # Define a variável de ambiente HUB_HOST
      
selenium-hub:
  image: selenium/hub:3.141.59
  container_name: selenium-hub
  ports:
    - "4444:4444"